branches: master
gemfile:
  - gemfiles/rails30.gemfile
  - gemfiles/rails31.gemfile
  - gemfiles/rails32.gemfile
language: ruby
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
before_script:
  - unset RAILS_ENV
  - unset RACK_ENV
